packages:
- '.'
extra-deps:
- base16-bytestring-1.0.1.0
- bitmap-0.0.2
- bitmap-opengl-0.0.1.5
- stb-image-0.2.1
- unicode-properties-3.2.0.0
- language-ecmascript-0.19.1.0
- github: lamdu/bindings-freetype-gl
  commit: abcb891cf2ed01edb2d02197ef2b354d6ff43db5
- github: lamdu/lamdu-calculus
  commit: fb1af1584ba8446359cb1fa435eefb8a024bc767
- github: lamdu/momentu
  commit: 136f28f027be13b657ca0c12ba74522590297aa8
- github: lamdu/hypertypes
  commit: 52beb9a91cebdaf18a3e7031a860e960cb086642
- github: lamdu/graphics-drawingcombinators
  commit: 39500dd189b0676468848d1f452ac31c7f0ec461
- github: lamdu/freetype2
  commit: 046328d92312d65638440132c016a3081d9c32a4
- github: lamdu/leveldb-haskell
  commit: 6f2f0b88fd7197e74cbff92bde94168adce3fb29
- github: lamdu/FreetypeGL
  commit: 18ca298d8fd48ad18f75264553b57714bf070c77
- github: lamdu/nodejs-exec
  commit: b42c7880973a6eed67dffcfb6641e84de07612f2

resolver: lts-17.8

allow-newer: true

ghc-options:
  # this is for weeder:
  "$locals": -fwrite-ide-info

# require-stack-version: ">=2.5"
